// types/index.ts
export type MediaItem = {
  id: string;
  title: string;
  imagePath: string;
  uxImage?: string;
  videoPath?: string;
  category: "UI/UX" | "Graphic Design" | "Shorts/Reels" | "Websites" | "Videos";
  subCategory?: string;
  description?: string;
  date?: string;
  views?: number;
  likes?: number;
  duration?: string; // For videos
  thumbnails?: string[]; // For image galleries
  url?: string; // For websites
  client?: string;
  tags?: string[];
};

// UI/UX Projects
export const uiuxProjects: MediaItem[] = [
  {
    id: "uiux-1",
    title: "Mobile Banking App Redesign",
    imagePath: "/work/uiux/th-ux1.png",
    uxImage: "/work/uiux/ui1.png",
    category: "UI/UX",
    description:
      "Complete redesign of a mobile banking application with focus on improved user experience and accessibility",
    date: "2025-03-15",
    client: "FinTech Solutions",
    tags: ["Mobile", "Finance", "UX Research", "Wireframing"],
  },
  {
    id: "uiux-2",
    title: "E-commerce Dashboard",
    imagePath: "/work/uiux/th-ux2.png",
    uxImage: "/work/uiux/ui2.png",
    category: "UI/UX",
    description:
      "Comprehensive merchant dashboard for e-commerce platform with analytics and inventory management",
    date: "2025-02-01",
    client: "ShopEasy Platform",
    tags: ["Dashboard", "Analytics", "E-commerce", "Admin Panel"],
  },
  {
    id: "uiux-3",
    title: "Fitness Tracking App",
    imagePath: "/samples/uiux/fitness-app.jpg",
    uxImage: "/samples/uiux/fitness-app-prototype.pdf",
    category: "UI/UX",
    description:
      "User-centered fitness application with progress tracking and personalized workout plans",
    date: "2025-01-10",
    client: "FitLife",
    tags: ["Mobile", "Health", "Activity Tracking", "Gamification"],
  },
  {
    id: "uiux-4",
    title: "Smart Home Control Interface",
    imagePath: "/samples/uiux/smart-home.jpg",
    category: "UI/UX",
    description:
      "Intuitive interface for controlling smart home devices with voice and touch interactions",
    date: "2024-12-05",
    client: "ConnectedHome Technologies",
    tags: ["IoT", "Smart Home", "Voice UI", "Touchscreen"],
  },
];

// Graphic Design Projects
export const graphicDesignProjects: MediaItem[] = [
  {
    id: "design-1",
    title: "Eco-Friendly Product Packaging",
    imagePath: "https://i.imgur.com/nR4dV6U.jpeg",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Packaging", "Eco-Friendly", "Product", "Sustainability"],
  },
  {
    id: "design-2",
    title: "Tech Conference Branding",
    imagePath: "https://i.imgur.com/OWIQX5n.jpeg",
    uxImage: "/samples/design/tech-conference-brand-guide.pdf",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Branding", "Conference", "Technology", "Event"],
  },
  {
    id: "design-3",
    title: "Annual Report Design",
    imagePath: "https://i.imgur.com/kTinACo.png",
    uxImage: "/samples/design/annual-report-2024.pdf",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Report", "Corporate", "Annual", "Print"],
  },
  {
    id: "design-4",
    title: "Food Delivery App Icons",
    imagePath: "https://i.imgur.com/2dOjunt.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Icons", "App", "Food", "Delivery"],
  },
  {
    id: "design-5",
    title: "Minimalist Poster Series",
    imagePath: "https://i.imgur.com/IDhYe6p.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Poster", "Minimalist", "Series", "Art"],
  },
  {
    id: "design-6",
    title: "Corporate Business Card Set",
    imagePath: "https://i.imgur.com/Llxfg24.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Business Card", "Corporate", "Stationery", "Identity"],
  },
  {
    id: "design-7",
    title: "Music Festival Flyer",
    imagePath: "https://i.imgur.com/Cf4RdTT.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Flyer", "Music", "Festival", "Event"],
  },
  {
    id: "design-8",
    title: "Children's Book Illustration",
    imagePath: "https://i.imgur.com/SbXOke2.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Illustration", "Children", "Book", "Story"],
  },
  {
    id: "design-9",
    title: "Restaurant Menu Design",
    imagePath: "https://i.imgur.com/kYZpMJw.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Menu", "Restaurant", "Food", "Print"],
  },
  {
    id: "design-10",
    title: "Social Media Ad Campaign",
    imagePath: "https://i.imgur.com/ALyqOcK.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Social Media", "Ad", "Campaign", "Marketing"],
  },
  {
    id: "design-11",
    title: "Event Invitation Card",
    imagePath: "https://i.imgur.com/j9aheTd.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Invitation", "Event", "Card", "Print"],
  },
  {
    id: "design-12",
    title: "Travel Brochure",
    imagePath: "https://i.imgur.com/ZQLCBKk.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Brochure", "Travel", "Tourism", "Print"],
  },
  {
    id: "design-13",
    title: "Fitness Brand Logo",
    imagePath: "https://i.imgur.com/0pqnL7H.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Logo", "Fitness", "Brand", "Identity"],
  },
  {
    id: "design-14",
    title: "Coffee Shop Loyalty Card",
    imagePath: "https://i.imgur.com/Eq30R8V.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Loyalty Card", "Coffee Shop", "Cafe", "Print"],
  },
  {
    id: "design-15",
    title: "Wedding Invitation Suite",
    imagePath: "https://i.imgur.com/VRhsolE.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Wedding", "Invitation", "Suite", "Event"],
  },
  {
    id: "design-16",
    title: "Nonprofit Awareness Poster",
    imagePath: "https://i.imgur.com/FL0Yxx0.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Poster", "Nonprofit", "Awareness", "Charity"],
  },
  {
    id: "design-17",
    title: "Fashion Lookbook Layout",
    imagePath: "https://i.imgur.com/SFRdr0X.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Lookbook", "Fashion", "Layout", "Style"],
  },
  {
    id: "design-18",
    title: "Podcast Cover Art",
    imagePath: "https://i.imgur.com/r0JbtU5.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Podcast", "Cover Art", "Audio", "Media"],
  },
  {
    id: "design-19",
    title: "E-book Cover Design",
    imagePath: "https://i.imgur.com/7qYOywZ.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["E-book", "Cover", "Design", "Digital"],
  },
  {
    id: "design-20",
    title: "Startup Pitch Deck Slides",
    imagePath: "https://i.imgur.com/M3ZOW4m.jpeg",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Pitch Deck", "Startup", "Slides", "Presentation"],
  },
  {
    id: "design-21",
    title: "Healthcare Infographic",
    imagePath: "https://i.imgur.com/YQZBaq7.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Infographic", "Healthcare", "Medical", "Visual"],
  },
  {
    id: "design-22",
    title: "Real Estate Signage",
    imagePath: "https://i.imgur.com/bgbY01y.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Signage", "Real Estate", "Property", "Outdoor"],
  },
  {
    id: "design-23",
    title: "Online Course Certificate",
    imagePath: "https://i.imgur.com/JEZWvvp.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Certificate", "Online Course", "Education", "Achievement"],
  },
  {
    id: "design-24",
    title: "Mobile App Splash Screen",
    imagePath: "https://i.imgur.com/OiCZCm5.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Splash Screen", "Mobile App", "UI", "Startup"],
  },
  {
    id: "design-25",
    title: "Holiday Greeting Card",
    imagePath: "https://i.imgur.com/slgcGMa.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Greeting Card", "Holiday", "Seasonal", "Print"],
  },
  {
    id: "design-26",
    title: "Tech Product Datasheet",
    imagePath: "/work/thumbnails/th26.png",
    category: "Graphic Design",
    subCategory: "Thumbnail",
    tags: ["Datasheet", "Tech Product", "Specification", "Print"],
  },
  {
    id: "design-27",
    title: "Tech Product Poster 1",
    imagePath: "/work/poster/ps1.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Tech Product", "Specification", "Print"],
  },
  {
    id: "design-28",
    title: "Tech Product Poster 2",
    imagePath: "/work/poster/ps2.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Tech Product", "Specification", "Print"],
  },
  // 39 more posters
  {
    id: "design-29",
    title: "Music Festival Poster",
    imagePath: "/work/poster/ps3.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Music", "Festival", "Event"],
  },
  {
    id: "design-30",
    title: "Art Exhibition Poster",
    imagePath: "/work/poster/ps4.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Art", "Exhibition", "Gallery"],
  },
  {
    id: "design-31",
    title: "Charity Run Poster",
    imagePath: "/work/poster/ps5.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Charity", "Run", "Event"],
  },
  {
    id: "design-32",
    title: "Movie Night Poster",
    imagePath: "/work/poster/ps6.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Movie", "Night", "Cinema"],
  },
  {
    id: "design-33",
    title: "Food Festival Poster",
    imagePath: "/work/poster/ps7.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Food", "Festival", "Event"],
  },
  {
    id: "design-34",
    title: "Tech Meetup Poster",
    imagePath: "/work/poster/ps8.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Tech", "Meetup", "Networking"],
  },
  {
    id: "design-35",
    title: "Book Fair Poster",
    imagePath: "/work/poster/ps9.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Book", "Fair", "Literature"],
  },
  {
    id: "design-36",
    title: "Startup Launch Poster",
    imagePath: "/work/poster/ps10.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Launch", "Business"],
  },
  {
    id: "design-37",
    title: "Photography Contest Poster",
    imagePath: "/work/poster/ps11.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Photography", "Contest", "Art"],
  },
  {
    id: "design-38",
    title: "Science Fair Poster",
    imagePath: "/work/poster/ps12.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Science", "Fair", "Education"],
  },
  {
    id: "design-39",
    title: "Sports Tournament Poster",
    imagePath: "/work/poster/ps13.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Sports", "Tournament", "Event"],
  },
  {
    id: "design-40",
    title: "Dance Competition Poster",
    imagePath: "/work/poster/ps14.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Dance", "Competition", "Event"],
  },
  {
    id: "design-41",
    title: "Environmental Awareness Poster",
    imagePath: "/work/poster/ps15.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Environment", "Awareness", "Green"],
  },
  {
    id: "design-42",
    title: "Health Camp Poster",
    imagePath: "/work/poster/ps16.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Health", "Camp", "Medical"],
  },
  {
    id: "design-43",
    title: "Coding Bootcamp Poster",
    imagePath: "/work/poster/ps17.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Coding", "Bootcamp", "Education"],
  },
  {
    id: "design-44",
    title: "Yoga Retreat Poster",
    imagePath: "/work/poster/ps18.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Yoga", "Retreat", "Wellness"],
  },
  {
    id: "design-45",
    title: "Fashion Show Poster",
    imagePath: "/work/poster/ps19.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Fashion", "Show", "Event"],
  },
  {
    id: "design-46",
    title: "Startup Pitch Poster",
    imagePath: "/work/poster/ps20.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Pitch", "Business"],
  },
  {
    id: "design-47",
    title: "Travel Expo Poster",
    imagePath: "/work/poster/ps21.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Travel", "Expo", "Tourism"],
  },
  {
    id: "design-48",
    title: "Gaming Tournament Poster",
    imagePath: "/work/poster/ps22.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Gaming", "Tournament", "Esports"],
  },
  {
    id: "design-49",
    title: "Startup Demo Day Poster",
    imagePath: "/work/poster/ps23.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Demo Day", "Business"],
  },
  {
    id: "design-50",
    title: "Marathon Poster",
    imagePath: "/work/poster/ps24.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Marathon", "Run", "Sports"],
  },
  {
    id: "design-51",
    title: "Startup Networking Poster",
    imagePath: "/work/poster/ps25.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Networking", "Business"],
  },
  {
    id: "design-52",
    title: "Film Festival Poster",
    imagePath: "/work/poster/ps26.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Film", "Festival", "Cinema"],
  },
  {
    id: "design-53",
    title: "Startup Hackathon Poster",
    imagePath: "/work/poster/ps27.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Hackathon", "Tech"],
  },
  {
    id: "design-54",
    title: "Startup Workshop Poster",
    imagePath: "/work/poster/ps28.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Workshop", "Business"],
  },
  {
    id: "design-55",
    title: "Startup Seminar Poster",
    imagePath: "/work/poster/ps29.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Seminar", "Business"],
  },
  {
    id: "design-56",
    title: "Startup Conference Poster",
    imagePath: "/work/poster/ps30.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Conference", "Business"],
  },
  {
    id: "design-57",
    title: "Startup Summit Poster",
    imagePath: "/work/poster/ps31.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Summit", "Business"],
  },
  {
    id: "design-58",
    title: "Startup Expo Poster",
    imagePath: "/work/poster/ps32.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Expo", "Business"],
  },
  {
    id: "design-59",
    title: "Startup Forum Poster",
    imagePath: "/work/poster/ps33.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Forum", "Business"],
  },
  {
    id: "design-60",
    title: "Startup Symposium Poster",
    imagePath: "/work/poster/ps34.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Symposium", "Business"],
  },
  {
    id: "design-61",
    title: "Startup Panel Poster",
    imagePath: "/work/poster/ps35.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Panel", "Business"],
  },
  {
    id: "design-62",
    title: "Startup Roundtable Poster",
    imagePath: "/work/poster/ps36.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Roundtable", "Business"],
  },
  {
    id: "design-63",
    title: "Startup Showcase Poster",
    imagePath: "/work/poster/ps37.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Showcase", "Business"],
  },
  {
    id: "design-64",
    title: "Startup Awards Poster",
    imagePath: "/work/poster/ps38.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Awards", "Business"],
  },
  {
    id: "design-65",
    title: "Startup Gala Poster",
    imagePath: "/work/poster/ps39.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Gala", "Business"],
  },
  {
    id: "design-66",
    title: "Startup Celebration Poster",
    imagePath: "/work/poster/ps40.png",
    category: "Graphic Design",
    subCategory: "Poster",
    tags: ["Poster", "Startup", "Celebration", "Business"],
  },
  {
    id: "design-68",
    title: "Startup Celebration Poster",
    imagePath: "/work/carousel/cr1.png",
    category: "Graphic Design",
    subCategory: "Carousel",
    tags: ["Poster", "Startup", "Celebration", "Business"],
  },
  {
    id: "design-69",
    title: "Startup Celebration Poster",
    imagePath: "/work/carousel/cr2.png",
    category: "Graphic Design",
    subCategory: "Carousel",
    tags: ["Poster", "Startup", "Celebration", "Business"],
  },
  {
    id: "design-70",
    title: "Creative Agency Carousel",
    imagePath: "/work/carousel/cr3.png",
    category: "Graphic Design",
    subCategory: "Carousel",
    tags: ["Poster", "Creative Agency", "Carousel", "Design"],
  },
  {
    id: "design-71",
    title: "Modern Portfolio Carousel",
    imagePath: "/work/carousel/cr4.png",
    category: "Graphic Design",
    subCategory: "Carousel",
    tags: ["Poster", "Portfolio", "Carousel", "Modern"],
  },
  {
    id: "design-72",
    title: "Business Growth Carousel",
    imagePath: "/work/carousel/cr5.png",
    category: "Graphic Design",
    subCategory: "Carousel",
    tags: ["Poster", "Business", "Growth", "Carousel"],
  },
];

// Shorts/Reels Projects
export const shortsReelsProjects: MediaItem[] = [
  {
    id: "shorts-1",
    title: "Product Launch Teaser",
    imagePath: "/samples/shorts/product-teaser.jpg",
    videoPath: "/samples/shorts/product-teaser.mp4",
    category: "Shorts/Reels",
    description: "15-second vertical video teasing a new smartphone release",
    date: "2025-04-10",
    duration: "0:15",
    views: 45000,
    likes: 3200,
    client: "TechGiant Mobile",
    tags: ["Product Launch", "Teaser", "Vertical Video", "Social Media"],
  },
  {
    id: "shorts-2",
    title: "Cooking Tutorial: 1-Minute Breakfast",
    imagePath: "/samples/shorts/cooking-tutorial.jpg",
    videoPath: "/samples/shorts/cooking-tutorial.mp4",
    category: "Shorts/Reels",
    description: "Quick recipe tutorial optimized for social media sharing",
    date: "2025-03-28",
    duration: "0:58",
    views: 125000,
    likes: 8700,
    client: "Quick Bites Cooking Channel",
    tags: ["Tutorial", "Cooking", "Fast-paced", "Educational"],
  },
  {
    id: "shorts-3",
    title: "Travel Destination Highlight",
    imagePath: "/samples/shorts/travel-highlight.jpg",
    videoPath: "/samples/shorts/travel-highlight.mp4",
    category: "Shorts/Reels",
    description: "Captivating 30-second showcase of a tropical destination",
    date: "2025-03-05",
    duration: "0:30",
    views: 87500,
    likes: 6400,
    client: "Wanderlust Travel Agency",
    tags: ["Travel", "Destination Marketing", "Scenic", "Wanderlust"],
  },
  {
    id: "shorts-4",
    title: "Workout Challenge",
    imagePath: "/samples/shorts/workout-challenge.jpg",
    videoPath: "/samples/shorts/workout-challenge.mp4",
    category: "Shorts/Reels",
    description: "Viral fitness challenge designed for social media engagement",
    date: "2025-02-20",
    duration: "0:22",
    views: 230000,
    likes: 15600,
    client: "FitLifestyle Brand",
    tags: ["Fitness", "Challenge", "Trendy", "User-generated Content"],
  },
];

// Websites Projects
export const websitesProjects: MediaItem[] = [
  {
    id: "web-1",
    title: "Luxury Real Estate Platform",
    imagePath: "/samples/websites/real-estate.jpg",
    category: "Websites",
    url: "https://luxury-homes-example.com",
    description:
      "High-end real estate website with immersive property showcases and virtual tours",
    date: "2025-04-15",
    client: "Elite Properties",
    tags: ["Real Estate", "Luxury", "Virtual Tours", "Property Listings"],
  },
  {
    id: "web-2",
    title: "Artisanal Bakery E-commerce",
    imagePath: "/samples/websites/bakery.jpg",
    category: "Websites",
    url: "https://sweet-delights-example.com",
    description:
      "Fully responsive e-commerce site for an artisanal bakery with online ordering",
    date: "2025-03-10",
    client: "Sweet Delights Bakery",
    tags: ["E-commerce", "Food & Beverage", "Online Ordering", "Responsive"],
  },
  {
    id: "web-3",
    title: "Nonprofit Organization Portal",
    imagePath: "/samples/websites/nonprofit.jpg",
    category: "Websites",
    url: "https://helping-hands-example.org",
    description:
      "Comprehensive website for a nonprofit with donation integration and volunteer management",
    date: "2025-02-05",
    client: "Helping Hands Foundation",
    tags: [
      "Nonprofit",
      "Donation Platform",
      "Volunteer Management",
      "Community",
    ],
  },
  {
    id: "web-4",
    title: "Medical Practice Website",
    imagePath: "/samples/websites/medical.jpg",
    category: "Websites",
    url: "https://wellness-clinic-example.com",
    description:
      "Professional healthcare provider website with appointment scheduling and patient resources",
    date: "2025-01-20",
    client: "Wellness Medical Group",
    tags: [
      "Healthcare",
      "Appointment Booking",
      "Patient Portal",
      "Medical Services",
    ],
  },
];

// Videos Projects
export const videosProjects: MediaItem[] = [
  {
    id: "video-1",
    title: "Sustainable Agriculture Documentary",
    imagePath: "/samples/videos/agriculture-doc.jpg",
    videoPath: "/samples/videos/agriculture-documentary.mp4",
    category: "Videos",
    subCategory: "Documentary",
    description:
      "In-depth documentary exploring innovative sustainable farming practices",
    date: "2025-04-20",
    duration: "26:42",
    client: "GreenEarth Initiative",
    tags: ["Documentary", "Agriculture", "Sustainability", "Educational"],
  },
  {
    id: "video-2",
    title: "Advanced Data Analysis Tutorial",
    imagePath: "/samples/videos/data-tutorial.jpg",
    videoPath: "/samples/videos/data-analysis-tutorial.mp4",
    category: "Videos",
    subCategory: "Educational Videos",
    description:
      "Comprehensive tutorial on advanced data analysis techniques for professionals",
    date: "2025-03-25",
    duration: "18:15",
    client: "DataMasters Academy",
    tags: ["Tutorial", "Data Science", "Professional Development", "Technical"],
  },
  {
    id: "video-3",
    title: "CEO Interview Series",
    imagePath: "/samples/videos/ceo-interview.jpg",
    videoPath: "/samples/videos/ceo-interview.mp4",
    category: "Videos",
    subCategory: "Talking Head",
    description:
      "Engaging interview with industry-leading CEO on business innovation",
    date: "2025-02-15",
    duration: "32:10",
    client: "Business Insider Magazine",
    tags: ["Interview", "Business", "Leadership", "Corporate"],
  },
  {
    id: "video-4",
    title: "Championship Highlights",
    imagePath: "/samples/videos/sports-highlights.jpg",
    videoPath: "/samples/videos/championship-highlights.mp4",
    category: "Videos",
    subCategory: "Sports",
    description:
      "Dynamic highlight reel from the national basketball championship",
    date: "2025-01-30",
    duration: "8:45",
    client: "National Basketball Association",
    tags: ["Sports", "Basketball", "Highlights", "Championship"],
  },
  {
    id: "video-5",
    title: "New Electric Vehicle Promotion",
    imagePath: "/samples/videos/ev-promo.jpg",
    videoPath: "/samples/videos/ev-promotion.mp4",
    category: "Videos",
    subCategory: "Promo/Ad",
    description:
      "Cinematic promotional video for latest electric vehicle model",
    date: "2025-01-05",
    duration: "1:45",
    client: "EcoMotors",
    tags: ["Advertisement", "Automotive", "Electric Vehicle", "Product Launch"],
  },
];

// Combine all category arrays into the final sampleData array
export const sampleData: MediaItem[] = [
  ...uiuxProjects,
  ...graphicDesignProjects,
  ...shortsReelsProjects,
  ...websitesProjects,
  ...videosProjects,
];

export default sampleData;
